"""add_position_status_realized_gain

Revision ID: 8f45b7a41fcf
Revises: 95798c4a2a9a
Create Date: 2026-06-16 22:29:20.446623

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8f45b7a41fcf'
down_revision = '95798c4a2a9a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('accounts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.add_column('positions', sa.Column('status', sa.String(length=10), nullable=False, server_default='OPEN'))
    op.add_column('positions', sa.Column('realized_gain', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('positions', sa.Column('realized_gain_pct', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('positions', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint('uq_position_sleeve_symbol', 'positions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_position_sleeve_symbol', 'positions', ['sleeve_id', 'symbol'])
    op.drop_column('positions', 'closed_at')
    op.drop_column('positions', 'realized_gain_pct')
    op.drop_column('positions', 'realized_gain')
    op.drop_column('positions', 'status')
    op.alter_column('accounts', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('accounts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
