"""add_weekly_portfolio_snapshots

Revision ID: afc155b89ef6
Revises: 8f45b7a41fcf
Create Date: 2026-06-19 16:27:44.495010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afc155b89ef6'
down_revision = '8f45b7a41fcf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_portfolio_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sleeve_id', sa.String(length=36), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('twr_period', sa.Float(), nullable=True),
    sa.Column('twr_cumul', sa.Float(), nullable=True),
    sa.Column('mwr_cumul', sa.Float(), nullable=True),
    sa.Column('cost_basis', sa.Float(), nullable=False),
    sa.Column('market_value', sa.Float(), nullable=False),
    sa.Column('cash_in', sa.Float(), nullable=False),
    sa.Column('cash_out', sa.Float(), nullable=False),
    sa.Column('realized_gain', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sleeve_id'], ['sleeves.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sleeve_id', 'week_start_date', name='uq_snapshot_sleeve_week')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_portfolio_snapshots')
    # ### end Alembic commands ###
